### ISSUE TITLE
해결하기 

### ISSUE THREAD

**Issue by ji-junhyuk** [42NoGun/Minishell#38]
- [x] exit 인자없이 들어올 때 세그폴트
- [x] unset home하고 cd 명령어 사용시 세그폴트
- [x] /tmp/heredoc, 좀 더 안전한 경로로 바꾸기
- [x] cat Makefile(|)cat -e
- [x] 중간에 인터럽트 들어왔을 때 릭이 난다(exit_status 도 이상함)
- [x] command not found -> exit_status 127?
- [x] export tmp="a                   b" -> 이상하게 담김
- [x] 공백만 입력으로 들어왔을 때 segfault

**Comment by ji-junhyuk** [comment]
bash 로직이 우리와 다름
- (ls) -> ls 1번 출력
- ((ls)) -> 출력 안함
- (ls && (ls)) -> ls 2번 출력
-  (((ls))) -> 출력 안함
- (ls && (ls) && ((ls))) -> ls 2번 출력
- (ls && (ls) && (ls && (ls))) -> ls 4번 출력 

- 우리는 ls갯수만큼 출력

**Comment by flowjiyun** [comment]
권한이 없는 실행 파일을 시행시키려고 할 때 exit status 는 126이다

**Comment by ji-junhyuk** [comment]
고생하셨어용
